import type { GameplayTemplate, GameplayTemplateId } from "./types";

export const GAMEPLAY_TEMPLATES: Record<GameplayTemplateId, GameplayTemplate> = {
  "fruit-drop-typer": {
    id: "fruit-drop-typer",
    label: "Fruit Drop Typer",
    kernel: "falling",
    mode: "falling-words",
    variant: "fruit",
    defaultWordlistIds: ["fruits"],
    defaultConfig: { durationSec: 60, scoreUnit: "score", fallSpeedPxSec: 58, spawnRateMs: 1400, livesAllowed: 3 },
    goal: "Type falling produce before it reaches the basket.",
    failureRule: "Missed fruit costs a life.",
    scoring: "score",
    visualMotif: "falling fruit and basket lane",
  },
  "food-rush-typer": {
    id: "food-rush-typer",
    label: "Food Rush Typer",
    kernel: "queue",
    mode: "classic-time",
    variant: "food-deliver",
    defaultWordlistIds: ["foods"],
    defaultConfig: { durationSec: 75, scoreUnit: "score" },
    goal: "Complete food tickets before the rush ends.",
    failureRule: "Typos slow the order flow and reduce accuracy.",
    scoring: "score",
    visualMotif: "restaurant tickets and serving counter",
  },
  "space-asteroid-splitter": {
    id: "space-asteroid-splitter",
    label: "Space Asteroid Splitter",
    kernel: "falling",
    mode: "falling-words",
    variant: "asteroid",
    defaultWordlistIds: ["space"],
    defaultConfig: { durationSec: 70, scoreUnit: "score", fallSpeedPxSec: 72, spawnRateMs: 1250, livesAllowed: 3 },
    goal: "Type asteroid labels to break them apart.",
    failureRule: "Asteroids that pass the shield cost a life.",
    scoring: "score",
    visualMotif: "asteroid field and shield line",
  },
  "ghost-chase-typer": {
    id: "ghost-chase-typer",
    label: "Ghost Chase Typer",
    kernel: "falling",
    mode: "falling-words",
    variant: "ghosts",
    defaultWordlistIds: ["horror"],
    defaultConfig: { durationSec: 70, scoreUnit: "score", fallSpeedPxSec: 58, spawnRateMs: 1350, livesAllowed: 3 },
    goal: "Type ghost names before they cross the hallway.",
    failureRule: "Escaped ghosts cost a life.",
    scoring: "score",
    visualMotif: "haunted hallway and drifting ghosts",
  },
  "horror-flashlight-typer": {
    id: "horror-flashlight-typer",
    label: "Horror Flashlight Typer",
    kernel: "falling",
    mode: "falling-words",
    variant: "spooky-chase",
    defaultWordlistIds: ["horror"],
    defaultConfig: { durationSec: 65, scoreUnit: "score", fallSpeedPxSec: 66, spawnRateMs: 1450, livesAllowed: 3 },
    goal: "Keep the light on by clearing scary prompts.",
    failureRule: "Letting prompts slip away drains the flashlight.",
    scoring: "score",
    visualMotif: "flashlight cone and dark hallway",
  },
  "racing-lane-typer": {
    id: "racing-lane-typer",
    label: "Racing Lane Typer",
    kernel: "lane",
    mode: "classic-time",
    variant: "race-typing",
    defaultWordlistIds: ["race"],
    defaultConfig: { durationSec: 75, scoreUnit: "wpm" },
    goal: "Type cleanly to push your racer down the lane.",
    failureRule: "Mistakes reduce accuracy and slow progress.",
    scoring: "wpm",
    visualMotif: "lane race with nitro-style progress",
  },
  "truck-dispatch-typer": {
    id: "truck-dispatch-typer",
    label: "Truck Dispatch Typer",
    kernel: "queue",
    mode: "classic-time",
    variant: "kph-truck",
    defaultWordlistIds: ["vehicles"],
    defaultConfig: { durationSec: 75, scoreUnit: "kph" },
    goal: "Process cargo and route terms at dispatch speed.",
    failureRule: "Unclean typing lowers dispatch accuracy.",
    scoring: "kph",
    visualMotif: "truck route board and cargo terminal",
  },
  "ten-key-cashier": {
    id: "ten-key-cashier",
    label: "10-Key Cashier",
    kernel: "form",
    mode: "countdown-defuse",
    variant: "number-pad",
    defaultWordlistIds: ["numbers"],
    defaultConfig: { durationSec: 80, scoreUnit: "score", spawnRateMs: 2400, livesAllowed: 3 },
    goal: "Enter numeric tickets before their timers expire.",
    failureRule: "Expired tickets cost a life.",
    scoring: "score",
    visualMotif: "cash register and numeric receipts",
  },
  "data-entry-warehouse": {
    id: "data-entry-warehouse",
    label: "Data Entry Warehouse",
    kernel: "queue",
    mode: "classic-time",
    variant: "profession-sim",
    defaultWordlistIds: ["professional"],
    defaultConfig: { durationSec: 90, scoreUnit: "kph" },
    goal: "Clear a warehouse queue of codes and office terms.",
    failureRule: "Typos reduce clean-entry accuracy.",
    scoring: "kph",
    visualMotif: "warehouse bins and entry queue",
  },
  "dispatch-call-queue": {
    id: "dispatch-call-queue",
    label: "Dispatch Call Queue",
    kernel: "queue",
    mode: "classic-time",
    variant: "profession-sim",
    defaultWordlistIds: ["professional"],
    defaultConfig: { durationSec: 90, scoreUnit: "kph" },
    goal: "Handle radio and call-center prompts in order.",
    failureRule: "Wrong characters lower call accuracy.",
    scoring: "kph",
    visualMotif: "radio console and incoming calls",
  },
  "medical-scribe-shift": {
    id: "medical-scribe-shift",
    label: "Medical Scribe Shift",
    kernel: "queue",
    mode: "classic-time",
    variant: "medical-sim",
    defaultWordlistIds: ["medical"],
    defaultConfig: { durationSec: 90, scoreUnit: "wpm" },
    goal: "Transcribe medical terms with high accuracy.",
    failureRule: "Mistakes lower clinical note accuracy.",
    scoring: "wpm",
    visualMotif: "clinic note queue and patient chart",
  },
  "transcript-repair": {
    id: "transcript-repair",
    label: "Transcript Repair",
    kernel: "queue",
    mode: "classic-time",
    variant: "medical-sim",
    defaultWordlistIds: ["medical", "professional"],
    defaultConfig: { durationSec: 90, scoreUnit: "wpm" },
    goal: "Repair transcript fragments by typing them cleanly.",
    failureRule: "Every miss lowers document accuracy.",
    scoring: "wpm",
    visualMotif: "transcript editor and correction marks",
  },
  "certificate-exam": {
    id: "certificate-exam",
    label: "Certificate Exam",
    kernel: "form",
    mode: "classic-time",
    variant: "certificate-ladder",
    defaultWordlistIds: ["certificate"],
    defaultConfig: { durationSec: 90, scoreUnit: "wpm" },
    goal: "Pass a short timed certificate round.",
    failureRule: "Low speed or accuracy means retry.",
    scoring: "wpm",
    visualMotif: "certificate gate and exam timer",
  },
  "speed-ladder": {
    id: "speed-ladder",
    label: "Speed Ladder",
    kernel: "lane",
    mode: "classic-time",
    variant: "speed-ladder",
    defaultWordlistIds: ["speed"],
    defaultConfig: { durationSec: 60, scoreUnit: "wpm" },
    goal: "Climb speed tiers with clean word streaks.",
    failureRule: "Typos break the ladder rhythm.",
    scoring: "wpm",
    visualMotif: "speed tiers and progress gates",
  },
  "accuracy-gate": {
    id: "accuracy-gate",
    label: "Accuracy Gate",
    kernel: "form",
    mode: "classic-time",
    variant: "speed-ladder",
    defaultWordlistIds: ["speed"],
    defaultConfig: { durationSec: 75, scoreUnit: "wpm" },
    goal: "Keep accuracy high while typing at pace.",
    failureRule: "Accuracy drops are the main penalty.",
    scoring: "wpm",
    visualMotif: "clean typing gate and error meter",
  },
  "rhythm-beat-typer": {
    id: "rhythm-beat-typer",
    label: "Rhythm Beat Typer",
    kernel: "rhythm",
    mode: "countdown-defuse",
    variant: "rhythm-lane",
    defaultWordlistIds: ["rhythm"],
    defaultConfig: { durationSec: 75, scoreUnit: "score", spawnRateMs: 1800, livesAllowed: 3 },
    goal: "Hit rhythm words before the beat window closes.",
    failureRule: "Expired beats cost a life.",
    scoring: "score",
    visualMotif: "beat lane and timing rings",
  },
  "lyric-beat-typer": {
    id: "lyric-beat-typer",
    label: "Lyric Beat Typer",
    kernel: "rhythm",
    mode: "countdown-defuse",
    variant: "rhythm-lane",
    defaultWordlistIds: ["rhythm"],
    defaultConfig: { durationSec: 75, scoreUnit: "score", spawnRateMs: 1900, livesAllowed: 3 },
    goal: "Type lyric-safe rhythm prompts on beat.",
    failureRule: "Missed beats cost a life.",
    scoring: "score",
    visualMotif: "lyric cards and pulse meter",
  },
  "keyboard-layout-quest": {
    id: "keyboard-layout-quest",
    label: "Keyboard Layout Quest",
    kernel: "target",
    mode: "spawn-targets",
    variant: "layout-map",
    defaultWordlistIds: ["keyboard"],
    defaultConfig: { durationSec: 75, scoreUnit: "score", spawnRateMs: 1350, livesAllowed: 3 },
    goal: "Clear key-layout targets across the board.",
    failureRule: "Crowded targets reduce control and accuracy.",
    scoring: "score",
    visualMotif: "keyboard map and key targets",
  },
  "dvorak-switch-quest": {
    id: "dvorak-switch-quest",
    label: "Dvorak Switch Quest",
    kernel: "target",
    mode: "spawn-targets",
    variant: "layout-map",
    defaultWordlistIds: ["keyboard"],
    defaultConfig: { durationSec: 80, scoreUnit: "score", spawnRateMs: 1450, livesAllowed: 3 },
    goal: "Practice layout-switch prompts and alternate key paths.",
    failureRule: "Mistakes reset the active target.",
    scoring: "score",
    visualMotif: "alternate keyboard layout map",
  },
  "right-hand-rescue": {
    id: "right-hand-rescue",
    label: "Right Hand Rescue",
    kernel: "target",
    mode: "spawn-targets",
    variant: "layout-map",
    defaultWordlistIds: ["keyboard"],
    defaultConfig: { durationSec: 70, scoreUnit: "score", spawnRateMs: 1400, livesAllowed: 3 },
    goal: "Clear right-hand key drills from moving targets.",
    failureRule: "Wrong keys reset target focus.",
    scoring: "score",
    visualMotif: "right-side keyboard lane",
  },
  "blindfold-home-row": {
    id: "blindfold-home-row",
    label: "Blindfold Home Row",
    kernel: "target",
    mode: "spawn-targets",
    variant: "layout-map",
    defaultWordlistIds: ["keyboard"],
    defaultConfig: { durationSec: 75, scoreUnit: "score", spawnRateMs: 1500, livesAllowed: 3 },
    goal: "Use home-row memory without looking down.",
    failureRule: "Mistakes break the memory streak.",
    scoring: "score",
    visualMotif: "home-row path and blindfold markers",
  },
  "language-script-sprint": {
    id: "language-script-sprint",
    label: "Language Script Sprint",
    kernel: "lane",
    mode: "classic-time",
    variant: "language-sprint",
    defaultWordlistIds: ["language-general"],
    defaultConfig: { durationSec: 75, scoreUnit: "wpm" },
    goal: "Practice language-specific prompt sets.",
    failureRule: "Typos reduce script accuracy.",
    scoring: "wpm",
    visualMotif: "language cards and script lane",
  },
  "alphabet-rocket": {
    id: "alphabet-rocket",
    label: "Alphabet Rocket",
    kernel: "target",
    mode: "spawn-targets",
    variant: "kids-playground",
    defaultWordlistIds: ["kids"],
    defaultConfig: { durationSec: 75, scoreUnit: "score", spawnRateMs: 1450, livesAllowed: 3 },
    goal: "Launch alphabet targets by typing simple words.",
    failureRule: "Too many missed targets ends the round.",
    scoring: "score",
    visualMotif: "alphabet rockets and launch pads",
  },
  "kids-playground": {
    id: "kids-playground",
    label: "Kids Playground",
    kernel: "target",
    mode: "spawn-targets",
    variant: "kids-playground",
    defaultWordlistIds: ["kids"],
    defaultConfig: { durationSec: 75, scoreUnit: "score", spawnRateMs: 1500, livesAllowed: 3 },
    goal: "Clear gentle short-word targets.",
    failureRule: "Missed targets reduce lives.",
    scoring: "score",
    visualMotif: "playground targets and bright prompts",
  },
  "tutor-monster-battle": {
    id: "tutor-monster-battle",
    label: "Tutor Monster Battle",
    kernel: "target",
    mode: "spawn-targets",
    variant: "kids-playground",
    defaultWordlistIds: ["kids"],
    defaultConfig: { durationSec: 80, scoreUnit: "score", spawnRateMs: 1400, livesAllowed: 3 },
    goal: "Defeat tutor monsters with short accurate words.",
    failureRule: "Uncleared monsters crowd the arena.",
    scoring: "score",
    visualMotif: "friendly monster arena",
  },
  "custom-arena-builder": {
    id: "custom-arena-builder",
    label: "Custom Arena Builder",
    kernel: "form",
    mode: "classic-words",
    variant: "custom-arena",
    defaultWordlistIds: ["custom"],
    defaultConfig: { wordCount: 40, scoreUnit: "score" },
    goal: "Complete a custom-style prompt set.",
    failureRule: "Skipped words count against clean completion.",
    scoring: "score",
    visualMotif: "rule cards and custom prompt board",
  },
  "word-search-scanner": {
    id: "word-search-scanner",
    label: "Word Search Scanner",
    kernel: "target",
    mode: "spawn-targets",
    variant: "typing-arcade",
    defaultWordlistIds: ["common-en"],
    defaultConfig: { durationSec: 75, scoreUnit: "score", spawnRateMs: 1500, livesAllowed: 3 },
    goal: "Find and type target words in an arcade field.",
    failureRule: "Wrong starts reset the active target.",
    scoring: "score",
    visualMotif: "word-search grid and scanner beam",
  },
  "typewriter-ribbon-rally": {
    id: "typewriter-ribbon-rally",
    label: "Typewriter Ribbon Rally",
    kernel: "lane",
    mode: "classic-time",
    variant: "retro-arcade",
    defaultWordlistIds: ["retro"],
    defaultConfig: { durationSec: 75, scoreUnit: "wpm" },
    goal: "Keep the ribbon moving with clean retro prompts.",
    failureRule: "Typos break the ribbon streak.",
    scoring: "wpm",
    visualMotif: "typewriter ribbon and paper feed",
  },
  "shop-gear-sorter": {
    id: "shop-gear-sorter",
    label: "Shop Gear Sorter",
    kernel: "falling",
    mode: "falling-words",
    variant: "shop-stack",
    defaultWordlistIds: ["shop"],
    defaultConfig: { durationSec: 70, scoreUnit: "score", fallSpeedPxSec: 60, spawnRateMs: 1450, livesAllowed: 3 },
    goal: "Sort falling shop and gear terms before they stack up.",
    failureRule: "Dropped items cost a life.",
    scoring: "score",
    visualMotif: "shop shelf and falling gear labels",
  },
  "boss-battle-typer": {
    id: "boss-battle-typer",
    label: "Boss Battle Typer",
    kernel: "target",
    mode: "spawn-targets",
    variant: "inspired-arcade",
    defaultWordlistIds: ["branded"],
    defaultConfig: { durationSec: 80, scoreUnit: "score", spawnRateMs: 1300, livesAllowed: 3 },
    goal: "Attack boss targets with themed prompt streaks.",
    failureRule: "Missed attacks let the boss pressure the arena.",
    scoring: "score",
    visualMotif: "arcade boss arena and attack targets",
  },
  "chicken-run": {
    id: "chicken-run",
    label: "Chicken Run",
    kernel: "target",
    mode: "spawn-targets",
    variant: "chicken",
    defaultWordlistIds: ["farm-animals"],
    defaultConfig: { durationSec: 75, scoreUnit: "score", spawnRateMs: 1700, livesAllowed: 3 },
    goal: "Type the word on each chicken before it sprints into the coop.",
    failureRule: "A chicken that reaches the coop costs a life.",
    scoring: "score",
    visualMotif: "farmyard lanes, fence, and a coop danger zone on the right",
  },
  "kph-meter": {
    id: "kph-meter",
    label: "KPH Pro Test",
    kernel: "queue",
    mode: "classic-time",
    variant: "profession-sim",
    defaultWordlistIds: ["numbers"],
    defaultConfig: { durationSec: 75, scoreUnit: "kph" },
    goal: "Key the data-entry codes exactly as shown — your live KPH and accuracy update in real time.",
    failureRule: "Errors lower the accuracy reading employers look for.",
    scoring: "kph",
    visualMotif: "clean data-entry console with a live KPH meter",
  },
};

export function getGameplayTemplate(id: GameplayTemplateId): GameplayTemplate {
  return GAMEPLAY_TEMPLATES[id];
}

export function listGameplayTemplates(): GameplayTemplate[] {
  return Object.values(GAMEPLAY_TEMPLATES);
}
